apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv
spec:
  storageClassName: pg-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/apps/testing-pg"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: apps
spec:
  storageClassName: pg-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pg-class
provisioner: kubernetes.io/no-provisioner